### ISSUE TITLE
This happened when I trying to compile 

### ISSUE THREAD

**Issue by sfsdfd62** [dincarnato/SHAPEwarp#1]
Unknown file type: ffi/Cargo.toml at /usr/local/lib/x86_64-linux-gnu/perl/5.30.0/FFI/Build/MM.pm line 149.
Could you help me with it? I offer my sincerest thanks to you !

**Comment by dincarnato** [comment]
Dear sfsdfd62,

this error comes from the FFI::Platypus Perl module.
I have a hunch... did you forget to install FFI::Platypus::Lang::Rust?

Danny

**Comment by sfsdfd62** [comment]
Dear dincarnato,

  Thank you for your reply. I checked my installation, and it seems that my FFI::Platypus::Lang::Rust has been updated to the newest version. And when I tried to run "make test ", this pops up.(Compiling procedure seems went fine)
<img width="924" alt="image" src="https://user-images.githubusercontent.com/93510728/184046920-77793416-9544-4970-9152-cc35239bc214.png">
  I am just a undergraduate and never expected receiving reply from people like you. Again I offer my heart-felt thanks. This really means a lot to me.

sfsdfd62

**Comment by dincarnato** [comment]
Dear sfsdfd62,

the screenshot you shared suggests that the issue is connected with the fact that you did not install the RNA Framework (or, that you did not add the path to RNA Framework's "lib/" folder to your PERL5LIB).

Danny

**Comment by sfsdfd62** [comment]
Dear dincarnato,

Oh, you are right. But after that, this bug comes up again. I 'm sure I have installed the newest  FFI and that FFI  Lang thing.
<img width="347" alt="image" src="https://user-images.githubusercontent.com/93510728/184351548-54cd1504-76a9-4538-b1f6-f89e8370d430.png">
<img width="920" alt="image" src="https://user-images.githubusercontent.com/93510728/184351678-7bb25b5c-5153-45e1-b46c-beb2c34b31b2.png">
Is it that I didn't add it into right path? What should I do? I really appreciate your help.

sfsdfd62

**Comment by dincarnato** [comment]
Dear sfsdfd62,

can I assume you solved the issue?

Danny
