### ISSUE TITLE
Trouble with SHAPEwarp install

### ISSUE THREAD

**Issue by MeganSylvia** [dincarnato/SHAPEwarp#3]
Hi! I have not used perl prior to now and am having a few issues with the final steps of the installation process.  I was able to install all the pre-requisites fine, but when I got to finally cloning and making SHAPEwarp, I received this error message with the Makefile.PL verbose command:
WARNING: PARENTNAME is not a known parameter.
  ABSTRACT => q[SHAPEwarp]
  BUILD_REQUIRES => { FFI::Build::File::Cargo=>q[0.07], FFI::Build::MM=>q[1.00] }
  CONFIGURE_REQUIRES => {  }
  DISTNAME => q[SW-KmerLookup]
  INSTALL_BASE => q[/home/mms95/perl5]
  NAME => q[SW::KmerLookup]
  PARENTNAME => q[SW::KmerLookup]
'PARENTNAME' is not a known MakeMaker parameter name.
  PREREQ_PM => { FFI::Platypus=>q[1.00], FFI::Platypus::Lang::Rust=>q[0.07] }
  TEST_REQUIRES => { Test2::V0=>q[0] }
  VERSION_FROM => q[lib/SW/KmerLookup.pm]
WARNING: Setting VERSION via file 'lib/SW/KmerLookup.pm' failed
 at /home/mms95/perl5/lib/perl5/ExtUtils/MakeMaker.pm line 741.
Using PERL=/usr/bin/perl
Generating a Unix-style Makefile
Writing Makefile for SW::KmerLookup
Writing MYMETA.yml and MYMETA.json

When running the make command I receive a warning message about kmer-lookup lib:
warning: fields `db_len` and `version` are never read
  --> kmer-lookup/src/db_format.rs:15:5
   |
13 | pub struct Reader<R> {
   |            ------ fields in this struct
14 |     reader: R,
15 |     db_len: u64,
   |     ^^^^^^
16 |     version: u16,
   |     ^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default
   = note: `Reader` has a derived impl for the trait `Debug`, but this is intentionally ignored during dead code analysis

warning: `kmer-lookup` (lib) generated 1 warning
   Compiling kmer-lookup-perl v0.1.0 (/usr/local/biocore/Bio_Programs/SHAPEwarp/ffi)
    Finished release [optimized] target(s) in 59.74s

Though ironically, when I run make test, I get the same output as posted in the manual:
"/usr/bin/perl" -MFFI::Build::MM=cmd -e fbx_build
"/usr/bin/perl" -MFFI::Build::MM=cmd -e fbx_test
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/basic.t .. ok   
All tests successful.
Files=1, Tests=1,  1 wallclock secs ( 0.01 usr  0.00 sys +  0.22 cusr  0.02 csys =  0.25 CPU)
Result: PASS

I was wondering if you had any advice? Because after this, as one might expect, the test script provided also did not run properly.

Thank you!

**Comment by dincarnato** [comment]
Hi MeganSylvia,

can you please give me some more detail? You said "as one might expect, the test script provided also did not run properly", but I would not expect that, because in the output you posted there is nothing wrong (just a couple of warnings that are normal and expected).
I tried getting SHAPEwarp from git on a clean linux install and it configured and ran smoothly for me.
Can you please post the full output you get when trying to run SHAPEwarp with the test data?

Thanks,
Danny

**Comment by MeganSylvia** [comment]
Hi Danny,

I appreciate the quick reply! I spent some time re configuring perl on this computer, as I think I may have made a few mistakes installing essential perl dependencies. Initially, I was getting an error message because the expected output table of the test analysis was empty and therefore not writing to the terminal. However, after doing a lot of messing around with perl programs today, it all of the sudden worked perfectly, so I am not sure what I fixed, but I believe the issue is fixed. I will let you know if I have any errors when I run my own samples!

**Comment by dincarnato** [comment]
Ok great!
Btw, in it's current implementation SHAPEwarp might be a bit slow, so using several processors might help speeding up the analysis. We have a new version of SHAPEwarp almost ready that will dramatically speed things up. Keep an eye on the repo cause that will make the difference!

All the best,
Danny

**Comment by MeganSylvia** [comment]
Hi Danny,

Thanks for the heads up! I look forward to it! I think this software has
really great promise. A suggestion though would be to include a utility to
convert csv or text files containing reactivity data to an xml file. My
data is coming from the StructureFold2 pipeline (Tack) and the conversion
is a bit complex for a novice.

**Comment by dincarnato** [comment]
Can you share one of such files? I can write a script to do the conversion. 

Also... have you considered using RNAFramework instead? ;-)

**Comment by MeganSylvia** [comment]
Of course! I have attached two example files. The first, example.react, is
the typical react file format that you use in the SF2 pipeline. This is a
multi-transcript file, where every transcript has two lines of information:
line 1: transcript id and line 2: reactivity at each nt position. No
sequence info is stored in this file. The second file I attached,
example.csv, is another filetype generated in the SF2 pipeline that
contains reactivity info. This is a 3 column csv that contains nt position,
transcript sequence and nt reactivity data. I was thinking it would be
easiest to use the second data type based on what the xml files look like.
I just haven't used xml before lol.

Thanks again!

**Comment by dincarnato** [comment]
Hi MeganSylvia,

sorry, I don't see any attachment. Can you try again? Or maybe just send it to me via email.
The XML files are the standard format used by the RNA Framework, which is why I was suggesting you to migrate to that platform instead of StructureFold2. It has all the same functions, plus many others and more customizations are possible.

Once you will send me the files I'll write you a script to convert to XML format.
Best,

Danny

**Comment by dincarnato** [comment]
I'm closing the issue, but if you have any other problem just let me know!

Best,
Danny
