### ISSUE TITLE
[!] Error: Invalid alignment format "--makePlot"

### ISSUE THREAD

**Issue by bmunn99** [dincarnato/SHAPEwarp#5]
Tried running SHAPEwarp after making my database and query file. The query file looks like this:

ANKHD1
TAATACGACTCACTATAGGACACGACTCGAGTAGAGTCGAATGATTGAATTGTTTGTTACAGTATTACAGACTGTCTCCCCTCTGAAGATACTACTGAAAATAGTAAAGACAGATATCCTGTACTAGAGATCTTATGGTGTGACTATGTATTTTGAAAGAAATCTCATTTATTTGATAGACAGCCTCATATGAAGTTACATGTGGATTAGGTAGAGGACAAATTAATATTATGTGCATTGTAAAGGTAGAAAGACTAAAACATAGGTGGTTATGCCATGGCCTTTTGACATTAGTGGCAGAATTGAATTGATAAGCCTTATCTTCTGTCAACCTAACCTATGGATTCTATACCATTTCTTTTTCCTAGATAATAGTGTTTAGAAATATAATTACAATTTGCACTTTTATACTTTTTTTTTTGTTGTTCTGCACTACCTGATTGATTGATGCACACTGAAGGAATTGGCAAATTGTCAACTGCTGATGGTAAAGCTTTTGCAGATCCTGAGGTACTCCGGAGACTGACATCCTCAGTTAGTTGTGCACTGGATGAAGCTGCTGCTGCACTGACACGGATGAAAGCAGAAAACAGCCACAATGCAGGACAAGTGGACACGTATGTGTTTAATGACTTTTGGATATTAGACATTTTCTTGAATAGATTTTGGGGAAGTAGCCAATTTTGGTTAAATATATCTTTTGGTGGAGCTTATAAACTTTAGCTGAAAGGATATTACATTTTAAGTGGATATATAAATGTATATGTATTATGTAGCTATACAAATGGATATTTTTGTTTCTTCATTCAGCTCTTATTCGTTGAGCATTCTTGTGGAATGTATTACACTAGAGTCTCTGAGAAATCCAAACTGAATAAGATCTGTTTTCCAGTTATAAGGAAGTTACTTATTCTAAAAGTTATTATAGTAAACTCTAAACCGAGACCGGAGTCGAGTGACTCCAACA
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.353668,1.016862,0.459786,0.376909,0.352406,0.304122,0.056392,0.761656,0.141341,0.304122,0.428257,0.390602,0.045402,0.072247,0.35592,0.017837,0.238361,0.667699,0.955966

Script looks like this: `SHAPEwarp --output ../ANKHD1_aln --query ../query/ANKHD1.txt --database ../ANKHD
1_db/ --threads 12 --reportAln --makePlot --matchKmerGCcontent`

It gives me the error: [!] Error: Invalid alignment format "--makePlot"

**Comment by dincarnato** [comment]
It looks like in your command line you are failing to provide an argument to the "--reportAln" parameter. Please check the help. The argument passed to reportAln can be fasta or stockholm.

Danny
