### ISSUE TITLE
Compilation Woes

### ISSUE THREAD

**Issue by ghost** [dincarnato/SHAPEwarp#6]
Hello!
I hope you are well -- I am unfamiliar with Perl, and having some trouble compiling SHAPEwarp on Ubuntu 18.04. When I run _make_ I get this as the output:
"/usr/bin/perl" -MFFI::Build::MM=cmd -e fbx_build

Which in itself I don't know is a good / bad thing. But when I run _make test_ it fails, and I get this:
t/basic.t .. Can't locate Core/Utils.pm in @ INC (you may need to install the Core::Utils module)

Which I'm pretty sure is not super great. So naturally (or naively) I tried to install Core::Utils in Perl (_install Core::Utils_), but it doesn't seem to be able to find it (which makes sense, I gather). I looked a little deeper into the error message from _make test_ and saw this:
BEGIN failed--compilation aborted at .../SHAPEwarp/blib/lib/SW/KmerLookup.pm line 4

Which looking at KmerLookup.pm line 4 reads: _use Core::Utils_, and I have officially gone full circle. When I run ./swKmerLookup with the input from issue #4 on the github I get a new error though:
Can't locate Core/Mathematics.pm in @ INC (you may need to install the Core::Mathematics module)
...
BEGIN failed--compilation aborted at ./swKmerLookup line 10

Which when looking at, seems to call:
use Core::Mathematics

Which, similar to Core::Utils, doesn't seem to be a CPAN package / something I can locate.

I assume I'm missing something pretty basic here. I made sure to install all the prerequisites, and RNAFramework is in my PATH (and the PERL5LIB). The other issue on the github re: compilation errors says it took some messing around with Perl install to fix, but I figured I'd check here before I start blindly playing around with Perl stuffs. 

Let me know if I can provide any other relevant information -- and thank you!
Lucy

**Comment by dincarnato** [comment]
Dear Lucy,

please refer to the docs and the README. As stated there:

SHAPEwarp builds on top of the [RNA Framework](https://github.com/dincarnato/RNAFramework/). To use SHAPEwarp, the lib/ folder of the RNA Framework must be added to the PERL5LIB environment variable:

`export PERL5LIB=$PERL5LIB:/path/to/RNAFramework/lib`

Hope this helps,
Danny

**Comment by ghost** [comment]
Hi Danny,

Thank you for the quick reply! Like I mentioned, I have already linked RNAFramework/lib to my PERL5LIB. I tried recompiling RNAFrameworks, as well as all the other prerequisites, and still get the same error on _make test_. 


I assume it is something wrong with either my RNAFrameworks, Perl, or some other missing prereq / mismatched compiler version or something. I'll go looking around their documentation to see if I messed something up / missed a prereq.

Thank you for the help!
Lucy

**Comment by dincarnato** [comment]
You might have multiple Perl installs on your system

**Comment by ghost** [comment]
I couldn't really track the issue down. I ended up compiling SHAPEwarp successfully on a different machine following all the same steps. Something about the environment of the first machine might have been jumbling things up -- unsure. 

Anyway, thank you -- I appreciate the fast replies.
Lucy
